debug: true
server:
  port: 3000

spring:
  application:
    name: why-journal-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/whyJournal
    username: user
    password: secret

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      platform: postgresql
      mode: never

  output:
    ansi:
      enabled: always

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR